# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container to /frontend
WORKDIR /frontend

# Copy the package.json and package-lock.json to install dependencies
COPY package.json .
COPY package-lock.json .

# Install dependencies
RUN npm install

# Copy the rest of the frontend application code to the container
COPY . .

# Expose port 3000 for the frontend app
EXPOSE 3000

# Run the frontend app using npm start
CMD ["npm", "start"]
