services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile.backend
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development  # Optional if using environment variables
      - APP_ENV_FILE=app/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/frontend
