version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile.backend
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - app/.env
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
